# Generated by Django 3.2.5 on 2021-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.SmallIntegerField(),
        ),
    ]
